### ISSUE TITLE
Why html & css isn't used/coded properly

### ISSUE THREAD

**Issue by DevT0ny** [BlocklyDuino/BlocklyDuino-v2#5]
I thought contributing on this but I could not even change height/margin/padding of title name. Looks like CSS is forced coded and HTML also.
Can I change it the way its written and also keeping UI good.

**Comment by SebCanet** [comment]
Hello,
the answer is simple: I'm not a good programmer!
But just a beginner who tinkers in the night with software that is useful for beginners, especially students in schools.

There is still some slag in the code because I test "hard" and then I try to formalize it properly. Sorry for the lack of quality.

What is not very visible is that I try to give back to BlocklyDuino its place as the backbone of all the forks that have been created since. Most of them started from Ardublockly or Blockly@rduino, which changed too much the original Blockly files to allow easy updates. So by making this v2 I wanted to start again on the clean base of Blockly and graft the necessary, but by deporting what is specific to the software in a folder (you can compare BlocklyDuino2 with STudio4Education to understand the idea). That way the forks would be easier and therefore their modifications would be easier to reintegrate into the common core afterwards.

Thank you very much for wanting to help!

**Comment by DevT0ny** [comment]
So you're making this software/repo more like as base of  blocklyduino, so others can use it. Is it ??
By the way you made so many projects and commits based on blocklyduino, my mind just blew away. 👏🏻👏🏻👏🏻

**Comment by SebCanet** [comment]
BlocklyDuino should be perfectly functionnal, by its own, like it is now.
And if someone wants to make his own fork for BlocklyESP (for example), he just change 'blocklyduino' folder, which aims is to keep all information specific to the fork (blocks, generator, css, etc). All the other are useful for the core of BlocklyDuino (ace editor, js functions, etc). I hope this is a good idea...and that you still want to help :-D

**Comment by SebCanet** [comment]
Cleaned (I hope so...).
